CREATE DATABASE IF NOT EXISTS library;
USE library;
CREATE TABLE IF NOT EXISTS library_records(book_id int PRIMARY KEY, book_name varchar(255), student_id int)
insert into library_records (book_id, book_name, student_id) values (199238803, 'morbi non quam nec', 871);
insert into library_records (book_id, book_name, student_id) values (164092751, 'risus dapibus augue vel', 5200);
insert into library_records (book_id, book_name, student_id) values (307006547, 'luctus et ultrices posuere cubilia curae', null);
insert into library_records (book_id, book_name, student_id) values (808909352, 'mauris lacinia sapien quis libero nullam sit', null);
insert into library_records (book_id, book_name, student_id) values (391566336, 'tortor risus dapibus augue vel accumsan', 2312);
insert into library_records (book_id, book_name, student_id) values (436230113, 'consectetuer eget rutrum', 4037);
insert into library_records (book_id, book_name, student_id) values (821944738, 'magnis dis', 3906);
insert into library_records (book_id, book_name, student_id) values (552404017, 'nulla nunc purus phasellus in felis donec', null);
insert into library_records (book_id, book_name, student_id) values (978104891, 'magna at nunc commodo', null);
insert into library_records (book_id, book_name, student_id) values (847757011, 'adipiscing molestie hendrerit at', null);
insert into library_records (book_id, book_name, student_id) values (934585860, 'nam ultrices libero non', null);
insert into library_records (book_id, book_name, student_id) values (149344517, 'morbi vestibulum velit id pretium', 4683);
insert into library_records (book_id, book_name, student_id) values (322155789, 'tellus nulla ut erat id mauris vulputate', null);
insert into library_records (book_id, book_name, student_id) values (471968968, 'eget massa tempor convallis', 6025);
insert into library_records (book_id, book_name, student_id) values (164130125, 'lacus curabitur at ipsum ac', 687);
insert into library_records (book_id, book_name, student_id) values (378918733, 'posuere cubilia curae nulla dapibus', 102);
insert into library_records (book_id, book_name, student_id) values (716965822, 'congue eget', 9267);
insert into library_records (book_id, book_name, student_id) values (446053428, 'primis in faucibus orci luctus et', 6010);
insert into library_records (book_id, book_name, student_id) values (517366481, 'eu orci mauris lacinia', 980);
insert into library_records (book_id, book_name, student_id) values (391409191, 'cum sociis', 4703);
insert into library_records (book_id, book_name, student_id) values (626322581, 'varius nulla facilisi cras non velit', 3491);
insert into library_records (book_id, book_name, student_id) values (957640609, 'vestibulum vestibulum ante ipsum', 7028);
insert into library_records (book_id, book_name, student_id) values (753560645, 'leo pellentesque ultrices', 8673);
insert into library_records (book_id, book_name, student_id) values (248901262, 'id lobortis convallis tortor risus dapibus', 721);
insert into library_records (book_id, book_name, student_id) values (296985295, 'in sapien iaculis', null);
insert into library_records (book_id, book_name, student_id) values (762678811, 'tortor risus dapibus augue vel accumsan tellus', 6147);
insert into library_records (book_id, book_name, student_id) values (561591196, 'volutpat erat', 6339);
insert into library_records (book_id, book_name, student_id) values (119024007, 'cubilia curae duis', 8327);
insert into library_records (book_id, book_name, student_id) values (104271532, 'enim leo rhoncus sed vestibulum sit', null);
insert into library_records (book_id, book_name, student_id) values (399297367, 'cras in purus eu magna vulputate', 7535);
insert into library_records (book_id, book_name, student_id) values (453222186, 'dictumst aliquam augue quam', null);
insert into library_records (book_id, book_name, student_id) values (660594289, 'vel ipsum praesent blandit lacinia erat vestibulum', 4198);
insert into library_records (book_id, book_name, student_id) values (163521051, 'amet eros suspendisse accumsan', 9414);
insert into library_records (book_id, book_name, student_id) values (675709851, 'tincidunt eget tempus vel pede morbi porttitor', null);
insert into library_records (book_id, book_name, student_id) values (365818317, 'dictumst aliquam augue', 5188);
insert into library_records (book_id, book_name, student_id) values (306267147, 'ultrices posuere cubilia curae mauris', 3123);
insert into library_records (book_id, book_name, student_id) values (277986410, 'id nisl venenatis lacinia aenean', 9493);
insert into library_records (book_id, book_name, student_id) values (677176811, 'eu interdum eu tincidunt', null);
insert into library_records (book_id, book_name, student_id) values (588300633, 'elementum nullam', 2077);
insert into library_records (book_id, book_name, student_id) values (994540645, 'ipsum primis in', 5058);
insert into library_records (book_id, book_name, student_id) values (615109926, 'donec posuere metus vitae ipsum aliquam', null);
insert into library_records (book_id, book_name, student_id) values (309016404, 'duis bibendum morbi non quam nec dui', 7477);
insert into library_records (book_id, book_name, student_id) values (141669757, 'primis in faucibus orci luctus', null);
insert into library_records (book_id, book_name, student_id) values (195255107, 'eu orci mauris', null);
insert into library_records (book_id, book_name, student_id) values (544216441, 'in hac habitasse platea dictumst', null);
insert into library_records (book_id, book_name, student_id) values (403195217, 'rutrum neque aenean auctor gravida sem praesent', 353);
insert into library_records (book_id, book_name, student_id) values (615834270, 'posuere cubilia curae donec pharetra magna vestibulum', 7740);
insert into library_records (book_id, book_name, student_id) values (103235062, 'lobortis vel dapibus', 5812);
insert into library_records (book_id, book_name, student_id) values (503845043, 'vel dapibus', null);
insert into library_records (book_id, book_name, student_id) values (305218297, 'metus aenean', 9294);
insert into library_records (book_id, book_name, student_id) values (226900882, 'lacus at', 7297);
insert into library_records (book_id, book_name, student_id) values (447522223, 'tincidunt nulla mollis molestie', 1364);
insert into library_records (book_id, book_name, student_id) values (559358563, 'ut erat id mauris vulputate', null);
insert into library_records (book_id, book_name, student_id) values (418959406, 'commodo placerat praesent blandit nam nulla', null);
insert into library_records (book_id, book_name, student_id) values (744097583, 'potenti cras in', 7592);
insert into library_records (book_id, book_name, student_id) values (878908337, 'in magna', 6126);
insert into library_records (book_id, book_name, student_id) values (895783451, 'libero nullam sit amet turpis elementum ligula', 5612);
insert into library_records (book_id, book_name, student_id) values (603163847, 'nullam varius nulla facilisi cras non', 9065);
insert into library_records (book_id, book_name, student_id) values (958471264, 'amet consectetuer adipiscing', null);
insert into library_records (book_id, book_name, student_id) values (531194189, 'vivamus in', 6433);
insert into library_records (book_id, book_name, student_id) values (311794129, 'at lorem integer tincidunt ante', null);
insert into library_records (book_id, book_name, student_id) values (290049180, 'vitae quam suspendisse potenti nullam porttitor', null);
insert into library_records (book_id, book_name, student_id) values (829607572, 'nam congue risus', 3200);
insert into library_records (book_id, book_name, student_id) values (938085619, 'tempus semper est quam pharetra magna ac', null);
insert into library_records (book_id, book_name, student_id) values (943343922, 'augue vestibulum ante ipsum', 1040);
insert into library_records (book_id, book_name, student_id) values (478570834, 'morbi non', 8114);
insert into library_records (book_id, book_name, student_id) values (693245337, 'est risus auctor sed tristique', null);
insert into library_records (book_id, book_name, student_id) values (926755360, 'vel est donec odio', 4016);
insert into library_records (book_id, book_name, student_id) values (983518431, 'condimentum curabitur in libero', 5483);
insert into library_records (book_id, book_name, student_id) values (897163524, 'ut blandit non interdum', 700);
insert into library_records (book_id, book_name, student_id) values (196032347, 'donec diam neque', null);
insert into library_records (book_id, book_name, student_id) values (263486097, 'metus aenean fermentum donec ut mauris eget', 4261);
insert into library_records (book_id, book_name, student_id) values (457132944, 'vel dapibus', 82);
insert into library_records (book_id, book_name, student_id) values (408039712, 'in hac habitasse platea', null);
insert into library_records (book_id, book_name, student_id) values (785048605, 'erat curabitur gravida nisi at', 7254);
insert into library_records (book_id, book_name, student_id) values (876323109, 'ridiculus mus vivamus vestibulum sagittis sapien', 1155);
insert into library_records (book_id, book_name, student_id) values (779108552, 'nisl duis bibendum felis', null);
insert into library_records (book_id, book_name, student_id) values (662459449, 'est et tempus semper est quam', 5743);
insert into library_records (book_id, book_name, student_id) values (712570857, 'non mattis pulvinar nulla pede', 7719);
insert into library_records (book_id, book_name, student_id) values (221399523, 'non lectus aliquam sit', 3987);
insert into library_records (book_id, book_name, student_id) values (426336457, 'nunc commodo', 5138);
insert into library_records (book_id, book_name, student_id) values (399580759, 'id ornare imperdiet sapien urna', 9653);
insert into library_records (book_id, book_name, student_id) values (768100497, 'lobortis sapien', 7790);
insert into library_records (book_id, book_name, student_id) values (992849686, 'rutrum neque aenean auctor gravida sem', null);
insert into library_records (book_id, book_name, student_id) values (303108437, 'ut at dolor quis', 6241);
insert into library_records (book_id, book_name, student_id) values (152295424, 'nulla eget', null);
insert into library_records (book_id, book_name, student_id) values (422907043, 'congue eget semper rutrum nulla', 3011);
insert into library_records (book_id, book_name, student_id) values (203657811, 'nullam molestie nibh in lectus pellentesque', 9564);
insert into library_records (book_id, book_name, student_id) values (793776455, 'justo lacinia eget tincidunt', 2762);
insert into library_records (book_id, book_name, student_id) values (895955463, 'sit amet lobortis sapien sapien non mi', 2595);
insert into library_records (book_id, book_name, student_id) values (158703547, 'amet eros suspendisse accumsan tortor quis turpis', 4880);
insert into library_records (book_id, book_name, student_id) values (842825803, 'in quam', 244);
insert into library_records (book_id, book_name, student_id) values (257965322, 'congue etiam justo etiam pretium', 9202);
insert into library_records (book_id, book_name, student_id) values (124420078, 'suspendisse potenti cras in', null);
insert into library_records (book_id, book_name, student_id) values (861123836, 'gravida nisi', 656);
insert into library_records (book_id, book_name, student_id) values (124866580, 'mattis nibh', null);
insert into library_records (book_id, book_name, student_id) values (832860620, 'interdum mauris non ligula pellentesque ultrices', 2189);
insert into library_records (book_id, book_name, student_id) values (909986306, 'integer non velit', 6805);
insert into library_records (book_id, book_name, student_id) values (943451460, 'pede lobortis', 451);
insert into library_records (book_id, book_name, student_id) values (999209547, 'volutpat dui', 8955);
